"use client";

import { FormEvent, useEffect, useState } from "react";
import { Building2, Loader2, Phone, UserRound, type LucideIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { AuthAlert, AuthField, AuthShell, AuthSubmit } from "@/components/auth/auth-ui";

const accountOptions: Array<{ value: string; label: string; icon: LucideIcon; description: string }> = [
  { value: "personal", label: "Personal", icon: UserRound, description: "Untuk penggunaan individu" },
  { value: "company", label: "Perusahaan", icon: Building2, description: "Untuk tim dan operasional" },
];

export default function OnboardingPage() {
  const [accountType, setAccountType] = useState("personal"); const [companyName, setCompanyName] = useState(""); const [companyPhone, setCompanyPhone] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  useEffect(() => { if (!localStorage.getItem("auth_token")) router.push("/login"); }, [router]);
  const handleSetup = async (event: FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { const token = localStorage.getItem("auth_token"); const base = `${process.env.NEXT_PUBLIC_SERVICE_RECOGNIZE_CCTV || ""}/api/v1/auth`; const response = await fetch(`${base}/setup-account`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ account_type: accountType, company_name: accountType === "company" ? companyName : undefined, company_phone: accountType === "company" ? companyPhone : undefined }) }); const data = await response.json(); if (!response.ok || !data.result?.user) throw new Error(data.message || data.detail || "Gagal mengatur akun."); localStorage.setItem("user_info", JSON.stringify(data.result.user)); router.push("/"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Gagal terhubung ke server."); } finally { setLoading(false); } };
  return <AuthShell eyebrow="Langkah terakhir" title="Siapkan workspace Anda" subtitle="Pilih cara Anda menggunakan Vision Admin agar dashboard dapat disesuaikan." footer={<span>Informasi ini dapat digunakan untuk pengaturan workspace Anda.</span>}><form className="space-y-5" onSubmit={handleSetup}>{error && <AuthAlert>{error}</AuthAlert>}<div className="grid grid-cols-2 gap-3">{accountOptions.map(({ value, label, icon: Icon, description }) => <button key={value} type="button" onClick={() => setAccountType(value)} className={`rounded-2xl border p-4 text-left transition ${accountType === value ? "border-indigo-500 bg-indigo-50 ring-4 ring-indigo-500/10" : "border-slate-200 bg-white hover:border-slate-300"}`}><span className={`mb-4 flex h-10 w-10 items-center justify-center rounded-xl ${accountType === value ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-500"}`}><Icon size={19} /></span><span className="block text-sm font-semibold text-slate-900">{label}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span></button>)}</div>{accountType === "company" && <div className="space-y-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><AuthField label="Nama perusahaan" icon={<Building2 size={18} />} type="text" required placeholder="PT Teknologi Maju" value={companyName} onChange={(event) => setCompanyName(event.target.value)} /><AuthField label="Nomor telepon (opsional)" icon={<Phone size={18} />} type="tel" placeholder="021-1234567" value={companyPhone} onChange={(event) => setCompanyPhone(event.target.value)} /></div>}{accountType === "personal" && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm leading-6 text-emerald-800">Akun personal Anda siap digunakan untuk mengelola seluruh fitur dashboard.</div>}<AuthSubmit loading={loading}>{loading ? <Loader2 size={19} className="animate-spin" /> : "Selesaikan Setup"}</AuthSubmit></form></AuthShell>;
}
